[GLOBAL]
pants_version = "2.33.0"
backend_packages = [
  "pants.backend.python",
  "pants.backend.python.lint.black",
]
pants_ignore.add = [
  "/multimodal_venv/",
  "/.venv/",
  "/dataset_pipeline_output/",
  "/data/multimodal_datapipeline/",
]

[anonymous-telemetry]
enabled = false

[source]
root_patterns = [
  "/",
  "/package",
]

[python]
interpreter_constraints = [">=3.10,<3.15"]
enable_resolves = true
default_resolve = "python-default"

[python.resolves]
python-default = "3rdparty/python/default.lock"

[python-infer]
unowned_dependency_behavior = "warning"

[generate-lockfiles]
diff = true

[black]
args = ["--line-length=120"]
